-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.avaliacao
(
    id serial NOT NULL,
    pergunta text COLLATE pg_catalog."default" NOT NULL,
    resposta text COLLATE pg_catalog."default" NOT NULL,
    feedback text COLLATE pg_catalog."default" NOT NULL,
    data timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT avaliacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avaliacoes
(
    id serial NOT NULL,
    pergunta_id integer,
    resposta integer NOT NULL,
    feedback text COLLATE pg_catalog."default",
    data_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT avaliacoes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.perguntas
(
    id serial NOT NULL,
    texto text COLLATE pg_catalog."default" NOT NULL,
    status boolean DEFAULT true,
    CONSTRAINT perguntas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.avaliacoes
    ADD CONSTRAINT avaliacoes_pergunta_id_fkey FOREIGN KEY (pergunta_id)
    REFERENCES public.perguntas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;